title       = "blockchain-info"
baseURL     = "https://blockchain-info-cli.tamnd.com/"
description = "A command line for blockchain-info."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/blockchain-info-cli"
